### ISSUE TITLE
main in Package.json

### ISSUE THREAD

**Issue by EliteScientist** [dfcreative/color-space#1]
In package.json your current main is configured to ./index.js

when we use webpack and require("color-space"); it uses this index.js. this index requires your husl.js. in your husl.js it has another require("husl"); the issue here is that in our configuration this resolves to itself since it checks the current folder first. it builds successfully but throws errors during runtime because _conv is undefined.

I ended up changing my requires to require("color-space/dist/color-space"); so that webpack finds your compiled version which fixed our issues.

What do you think of changing your main: to dist/color-space.js? so that people can use require("color-space") ?

**Comment by dfcreative** [comment]
`dist/color-space` is built to use as a standalone module, so it exposes global `colorSpace` in case if you don’t use any commonJS wrapper.
It seems to be the issue of webpack, have you looked up for the solution on that? Browserify builds it just fine.
BTW, do you use that husl color space? I can just exclude it from the `index.js`, it is quite uncommon space and adds up extra size to build.

**Comment by EliteScientist** [comment]
We do use a CommonsJS wrapper. We don't use the husl colors pace at all.

Excluding it would be awesome.

**Comment by dfcreative** [comment]
actually you can include only the color-spaces you use, the size of build will be minimal: require('color-space/hsl')

**Comment by EliteScientist** [comment]
I prefer that method, I'll talk to our developer that used the lib and have him only require the spaces used.

Thanks!

**Comment by dfcreative** [comment]
Ok. So I’ll close this, as this seem to be the issue of webpack.
@sokra, please have a look.

**Comment by sokra** [comment]
Works fine for me. Maybe a incorrect configuration.

**Comment by EliteScientist** [comment]
Probably our configuration. we have a very complicated configuration where webpack configs are generated at build time for each component and components are compiled separately. 

I'll make sure that we only require whats necessary instead of the entire index.

Thanks for your help.
